### ISSUE TITLE
Examples are not working?

### ISSUE THREAD

**Issue by marcosnils** [jiweibo/SSOCR#1]
Just tried this project with the latest opencv and matplotlib versions and I'm getting a division by zero error?. 

Any advise?

**Comment by jiweibo** [comment]
Sorry to be late to replay. Do you solve the problem?

There are two types of digits for universal electric meter. One is tilted (for this project), the other is normal. If your image is normal then maybe you should modify the “recognize_digits_line_method” function.

Can you post the image to help me fix this bug?
