### ISSUE TITLE
integer division or modulo by zero

### ISSUE THREAD

**Issue by yuanchi** [jiweibo/SSOCR#2]
I followed the instruction inputing: python ssocr.py images/test1.bmp -s
Error messages happened: 
File "ssocr.py", line 252, in recognize_digits_line_method
    if cv2.countNonZero(roi[h - int(3 * width / 4):h, w - int(3 * width / 4):w]) / (9 / 16 * width * width) > 0.65:
ZeroDivisionError: integer division or modulo by zero

I changed the testing images from test2.bmp to test2.bmp, the results were the same.

**Comment by jiweibo** [comment]
I guess you used the python2 interpreter. 
Error message shows that zero division. The denominator is 9 / 16 * width ^2.  In python2, this will be evaluated to 0, but ok in python3. 
You should fix 9/16 to 9./16 or use
`from  __future__ import division`

**Comment by yuanchi** [comment]
Thanks for replying so quickly.
It's exactly python version issue.
And I've tested it with 9./16, everything almost works fine.
But when it comes with test2.bmp, '1' can't be detected or identified.
Now, I use python 3.x, and it works as expected.

**Comment by yuanchi** [comment]
Another issue for python 2 is encoding.
When it meets Simplified Chinese, it stops running.
I put '# encoding: utf-8' on the top of ssocr.py, the problem is solved.

**Comment by jiweibo** [comment]
I have fixed the encoding problem for python2.x. Thanks for your advice.
